CREATE TABLE organization (
    id                     NUMBER(5, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_name           VARCHAR2(100) default ' ',
    years_of_incorporation NUMBER(5, 0) default 0,
    postal_code            VARCHAR2(10) default ' ',
    employee_count         NUMBER(10) default 0,
    slogan                 VARCHAR2(500) default ' '
);
insert into organization(company_name,years_of_incorporation,postal_code,employee_count,slogan) values('FIS GLOBAL','1992','605007','62000','WORK HARD');
insert into organization(company_name,years_of_incorporation,postal_code,employee_count,slogan) values('APISERO','2016','605001','668','WORK HARD');
COMMIT;
select s.* from organization s;
